# Site settings
title: Max Böck - Frontend Web Developer
description: > 
  Max Böck is a professional frontend developer based in Vienna, Austria.
baseurl: ""
url: https://mxb.at
repo: https://github.com/maxboeck/mxb
email: hello@mxb.at
permalink: /blog/:slug/

# SEO/Meta settings
author: Max Böck
twitter:
  username: mxbck
github:
  username: maxboeck
facebook:
  app_id: 127677017332959
  admins: 100000249390604
social:
  name: Max Böck
  links:
    - https://twitter.com/mxbck
    - https://github.com/maxboeck
    - https://keybase.io/mxb
seo:
  name: Max Böck
  type: Person

webmentions:
  username: mxb.at
  cache_folder: _cache
  cache_bad_uris_for: 5
  legacy_domains:
    - http://mxb.at
    - http://www.mxb.at
  js:
    destination: _assets/js
    deploy: false
    uglify: false

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/logo.jpg
  - scope:
      path: ""
      type: posts
    values:
      feed: true
      is_post: true
      layout: post

#Custom collections
collections:
  projects:
    output: true
    permalink: /project/:path/

# Pagination
paginate: 20
paginate_path: "/blog/page/:num/"

# Markdown settings
markdown: kramdown
highlighter: rouge

# Includes
include:
  - _pages

# Build settings
exclude:
  - package.json
  - gulpfile.babel.js
  - ftpconfig.js
  - README.md
  - LICENSE
  - _tasks
  - assets
  - node_modules
  - Gemfile
  - Gemfile.lock
  - "*.sublime-*"

#Files generated by Gulp
keep_files:
  - assets

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-email-protect
  - jekyll-postfiles
  - jekyll-webmention_io