source "https://rubygems.org"

gem "jekyll"
gem "jekyll-feed"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "jekyll-email-protect"
gem "jekyll-postfiles"
gem "jekyll-webmention_io"